### ISSUE TITLE
What is unit_normals_of?

### ISSUE THREAD

**Issue by kant2002** [hacklex/CuteCAS#1]
If run `fstar .\IntRingExample.fst` you will receive error `.\IntRingExample.fst(52,31-52,46): (Error 72) Identifier not found: [unit_normals_of]`
I assume this is line.
https://github.com/hacklex/CuteCAS/blob/254f81f0e237a8b7a177c16f6bceb7cb27c1d65d/IntRingExample.fst#L52

**Comment by hacklex** [comment]
IntRingExample is one of my sandbox modules. It is of little use on its own, especially now that it does not reflect the current state of AlgebraTypes. Perhaps I should remove it altogether from the repository.

Regarding your question, you may want to refer to Geddes, Czapor, Labahn -- Algorithms for Computer Algebra (p.27) for a good read on the concept of unit*normal decomposition, but I'll try to keep it short:

For an arbitrary integral domain (i.e. commutative ring with no zero divisors), we call `a` and `b` associated, or, equivalently, `a is associated with b` when we have `a divides b` and `b divides a` at the same time.
For integers, associated elements are just pairs `{-a, a}`. Things get more interesting when you consider other rings, be it K[x] or Z[t] where t is algebraic. 

But anyway you usually naturally have a criterion to single out one element from each associate class and treat it as its canonical representative, and call it `unit normal`. For integers, unit normals are just nonnegative numbers.

This way, for exmaple, you can decompose gaussian integers into a `unit` (-1, -i, +1, or +i) times `non-negative integer`.
This concept is in fact quite general, and applies not only to numeric rings, but also to the rings of polys.

The current definition is [here](https://github.com/hacklex/CuteCAS/blob/254f81f0e237a8b7a177c16f6bceb7cb27c1d65d/AlgebraTypes.fst#L846).

Below in that file are some lemmas and basic properties stated. 

Currently, then notions of euclidean domains are largely unused. They'll soon become useful when I get to implement the euclidean algorithm (GCD/EEA) and the lemmas that would lead to construction of reduced fractions over commutative domains where gcd/eea are well-enough-defined.
